FROM mysql:latest

# Configuración de la base de datos
ENV MYSQL_ROOT_PASSWORD=Esteb@nquito1
ENV MYSQL_DATABASE=TodoListDB
ENV MYSQL_USER=sa
ENV MYSQL_PASSWORD=Esteb@nquito1

# Exponer el puerto
EXPOSE 3306
